<?php

namespace CookbookBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RecipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecipeRepository extends EntityRepository
{

    public function findAllOrderedByTitle()
    {
        return $this->createQueryBuilder('r')
            ->orderBy('r.category', 'ASC')
            ->getQuery()
            ->getResult();
    }

    public function findRecipesByTitle($recipeTitle)
    {
        $splitPattern = '/[;, ]/';
        $searchTerms = preg_split($splitPattern, $recipeTitle);

        $qb = $this->createQueryBuilder('r');

        foreach ($searchTerms as $key => $searchTerm) {
            $qb->andWhere('r.title LIKE :searchTerm' . $key)
                ->setParameter('searchTerm' . $key, "%$searchTerm%");
        }

        $result = $qb->getQuery()
            ->getResult();

        return $result;
    }

    /*
    public function findRecipesByCategory($categoryName)
    {
        return $this->createQueryBuilder('r')
            ->leftJoin('r.category', 'c')
            ->where('c.name LIKE :categoryName')
            ->setParameter('categoryName', $categoryName)
            ->getQuery()
            ->getResult();
    }

    public function findRecipesByIngredients($ingredientNames)
    {
        $ingredients = array();

        foreach ($ingredientNames as $ingredientName) {
            if (!empty($ingredientName)) {
                $ingredients[] = $this->findIngredientByName($ingredientName);
            }
        }

        $result = $this->createQueryBuilder('r')
            ->leftJoin('r.ingredients', 'ri')
            ->where('ri.ingredient IN (:ingredients)')
            ->setParameter('ingredients', $ingredients)
            ->getQuery()
            ->getResult();

        return $result;
    }

    public function findRecipesByTags($tagNames)
    {
        $tags = array();

        foreach ($tagNames as $tagName) {
            if (!empty($tagName)) {
                $tags[] = $this->findTagByName($tagName);
            }
        }

        $result = $this->createQueryBuilder('r')
            ->leftJoin('r.tags', 'rt')
            ->where('rt.tag IN (:tags)')
            ->setParameter('tags', $tags)
            ->getQuery()
            ->getResult();

        return $result;
    }

    public function findRecipesWithPhoto()
    {
        return $this->createQueryBuilder('r')
            ->where('r.imagePath IS NOT NULL')
            ->getQuery()
            ->getResult();
    }
*/

    public function findRecipes($title, $category, $ingredientNames, $tagNames, $dietaryRecipeTags, $withPhoto)
    {
        $splitPattern = '/[;, ]/';
        $searchTerms = preg_split($splitPattern, $title);

        $ingredients = array();
        $tags = array();
        $dietaryTags = array();

        foreach ($ingredientNames as $ingredientName) {
            if (!empty($ingredientName)) {
                $foundIngredients = $this->findIngredientByName($ingredientName);
                foreach ($foundIngredients as $foundIngredient) {
                    $ingredients[] = $foundIngredient;
                }
            }
        }

        foreach ($tagNames as $tagName) {
            if (!empty($tagName)) {
                $foundTags = $this->findTagByName($tagName);
                foreach ($foundTags as $foundTag) {
                    $tags[] = $foundTag;
                }
            }
        }

        foreach ($dietaryRecipeTags as $dietaryRecipeTag) {
            if (!empty($dietaryRecipeTag)) {
                $foundTags = $this->findTagByName($dietaryRecipeTag->getTag()->getName());
                foreach ($foundTags as $foundTag) {
                    $dietaryTags[] = $foundTag;
                }
            }
        }

        $qb = $this->createQueryBuilder('r');

        if (count($searchTerms) > 0) {
            foreach ($searchTerms as $key => $searchTerm) {
                $qb->andWhere('r.title LIKE :searchTerm' . $key)
                    ->setParameter('searchTerm' . $key, "%$searchTerm%");
            }
        }

        if ($category) {
            $categoryName = $category->getName();
            $qb->leftJoin('r.category', 'c')
                ->andWhere('c.name LIKE :categoryName')
                ->setParameter('categoryName', $categoryName);
        }

        if (count($ingredients) > 0) {
            $qb->leftJoin('r.ingredients', 'ri')
                ->andWhere('ri.ingredient IN (:ingredients)')
                ->setParameter('ingredients', $ingredients);
        }

        if (count($dietaryTags) > 0) {
            $qb->leftJoin('r.tags', 'rt')
                ->andWhere('rt.tag IN (:dietaryTags)')
                ->setParameter('dietaryTags', $dietaryTags);
        }

        if (count($tags) > 0) {
            $qb->andWhere('rt.tag IN (:tags)')
                ->setParameter('tags', $tags);
        }

        if ($withPhoto) {
            $qb->andWhere('r.imagePath IS NOT NULL');
        }


        $results = $qb->getQuery()
            ->getResult();

        return $results;
    }

    private function findIngredientByName($ingredientName)
    {
        return $this->getEntityManager()->createQueryBuilder()
            ->select('i')
            ->from('CookbookBundle:Ingredient', 'i')
            ->where('i.name LIKE :ingredientName')
            ->setParameter('ingredientName', "%$ingredientName%")
            ->getQuery()
            ->getResult();
    }

    private function findTagByName($tagName)
    {
        return $this->getEntityManager()->createQueryBuilder()
            ->select('t')
            ->from('CookbookBundle:Tag', 't')
            ->where('t.name LIKE :tagName')
            ->setParameter('tagName', "%$tagName%")
            ->getQuery()
            ->getResult();
    }
}
